<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>items</key>
	<array>
		<dict>
			<key>assets</key>
			<array>
				<dict>
					<key>kind</key>
					<string>software-package</string>
					<key>url</key>
					<string>https://www.mediafire.com/file/9qisok98q9jxg2e/Delta_2.639.688_1724717088.ipa/file</string>
				</dict>
			</array>
			<key>metadata</key>
			<dict>
				<key>bundle-identifier</key>
				<string>com.gloob.deltamobile</string>
				<key>bundle-version</key>
				<string>2.639.688</string>
				<key>kind</key>
				<string>software</string>
				<key>title</key>
				<string>Delta</string>
			</dict>
		</dict>
	</array>
</dict>
</plist>
